### ISSUE TITLE
Arrow functions break when Uglifying for production

### ISSUE THREAD

**Issue by CharlieIGG** [bradleyflood/string-title-case#1]
Just a heads up:

Anyone trying to use the stable version of UglifyJS (pretty much anyone using webpack) will have issues with this library because of arrow functions when compiling for production.

You might want to transpile the code here.

**Comment by bradfx** [comment]
Thanks for letting me know. I'll look into it.

**Comment by bradfx** [comment]
So I'm assuming you are referring to Uglify reporting `Parse error: Unexpected token: operator (>)` ? This package is written in ES6 so you will need to either:

1. Use the new ES6 compatible edition of uglify,  [uglify-es](https://www.npmjs.com/package/uglify-es), or 
2. Transpile your code down to ES5 first.

Thank you for reporting!

**Comment by CharlieIGG** [comment]
Yeah I did this

> Transpile your code down to ES5 first.

May be worth at least adding to README
