### ISSUE TITLE
Words inside braces

### ISSUE THREAD

**Issue by ror-y** [bradleyflood/string-title-case#2]
Please could you add support for words inside braces?

For example in my case, I have the country `VIRGIN ISLANDS (BRITISH)` which turns into `Virgin Islands (british)`, rather than the expected `British`.

**Comment by bradfx** [comment]
Good idea. Now done in v`3.0.0` c39522d15e3e0e5ff70abfc4ad6c0960c8df100d Check it out

**Comment by bradfx** [comment]
Actual code here -> https://github.com/bradleyflood/string-title-case/commit/d07e3b040669c01a56637f29e540ee6dbce87723
